tweetapp/urls.py
from django.urls import path
from .views import (Home,RetweetedTweetListView,RetweetedTweetUserListView, 
ListRetweetedUser, ViewSearchTweeterUser, ViewSearchTweet )

urlpatterns = [

    path('',
         Home.as_view(),
         name='home'),
    path('retweets_of_me/',
         RetweetedTweetListView.as_view(),
         name='retweets_of_me'),

    path('retweet_user_list/<int:tweet_id>/',
         RetweetedTweetUserListView.as_view(),
         name='retweet_user_list'),


     path('retweeted_user/',
      ListRetweetedUser.as_view(), 
      name='retweeted_user'),

     path('search_user/',
      ViewSearchTweeterUser.as_view(), 
      name='search_user'),
      
     path('search_tweet/',
      ViewSearchTweet.as_view(), 
      name='search_tweet'),

]

twitterapi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include(('tweetapp.urls', 'tweetapp'), namespace='tweetapp')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

tweetapp/models.py
from django.db import models
from django.utils.translation import gettext, gettext_lazy as _
from django.db.models.signals import post_save
from django.core.validators import MinValueValidator, MaxValueValidator

tweetapp/forms.py
from email.policy import default
from django import forms


class FormSearchTweeterUser(forms.Form):
    query = forms.CharField(label='Find People')



class FormSearchTweet(forms.Form):
    query = forms.CharField(label='Search Tweet')

tweetapp/views.py
import logging

import tweepy
from django.conf import settings
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .forms import FormSearchTweeterUser, FormSearchTweet

logger = logging.getLogger(__name__)

# disable the tweepy, requests_oauthlib and oauthlib.oauth1 lib logs
logging.getLogger('tweepy').setLevel(logging.WARNING)
logging.getLogger('requests_oauthlib').setLevel(logging.WARNING)
logging.getLogger('oauthlib.oauth1').setLevel(logging.WARNING)


TWEET_AUTH = tweepy.OAuth1UserHandler(settings.API_KEY,
                                      settings.API_SECRET_KEY,
                                      settings.ACCESS_TOKEN,
                                      settings.ACCESS_TOKEN_SECRET,
                                      )

TWEET_API = tweepy.API(TWEET_AUTH)



class Home(TemplateView):
    template_name = 'home.html'


class RetweetedTweetListView(TemplateView):
    template_name = 'retweeted_tweet_list.html'

    def get_context_data(self, **kwargs):
        context = TemplateView.get_context_data(self, **kwargs)
        context['get_retweets_of_me'] = TWEET_API.get_retweets_of_me()
        return context


class RetweetedTweetUserListView(TemplateView):
    template_name = 'retweeted_tweet_user_list.html'

    def get_context_data(self, **kwargs):
        context = TemplateView.get_context_data(self, **kwargs)
        tweet_id = self.kwargs.get('tweet_id')
        # print(tweet_id)
        retweets = TWEET_API.get_retweets(tweet_id)
        context['get_retweets'] = retweets
        return context


class ViewSearchTweeterUser(FormView):
    form_class = FormSearchTweeterUser
    template_name = 'form_search_user.html'
    success_url = reverse_lazy('tweetapp:search_user')

    def form_valid(self,form, *args, **kwargs):
        query = form.cleaned_data['query']
        search_users = TWEET_API.search_users(query)
        context = TemplateView.get_context_data(self, **kwargs)
        context['search_users'] = search_users

        if 'form' not in context:
            context['form'] = self.get_form()


        # return FormView.form_valid(self, form, **kwargs)
        return self.render_to_response(context=context)


class ViewSearchTweet(FormView):
    form_class = FormSearchTweet
    template_name = 'form_search_tweet.html'
    success_url = reverse_lazy('tweetapp:search_tweet')

    def form_valid(self,form, *args, **kwargs):
        query = form.cleaned_data['query']
        search_tweets = TWEET_API.search_tweets(query)
        context = TemplateView.get_context_data(self, **kwargs)
        context['search_tweets'] = search_tweets

        if 'form' not in context:
            context['form'] = self.get_form()

        # return FormView.form_valid(self, form, **kwargs)
        return self.render_to_response(context=context)



class ListRetweetedUser(TemplateView):
    template_name = 'retweeted_user.html'

    def get_context_data(self, **kwargs):
        context = TemplateView.get_context_data(self, **kwargs)

        retweet_user_list = []
        # get my retweeted tweets
        # Returns the 20 most recent Tweets of the authenticated user that have been retweeted by others.
        my_retweets = TWEET_API.get_retweets_of_me()
        # for every retweeted tweets get the retweetd users of my retweeted tweet
        for mt in my_retweets:
            # Returns up to 100 of the first Retweets of the given Tweet.
            retweets = TWEET_API.get_retweets(mt.id)
            retweets_user = [rt.user for rt in retweets]
            retweet_user_list.append(retweets_user)
        # convert list from nested list to one dimensional list
        unique_user_list = [u for u_l in retweet_user_list for u in u_l]

        # make unique user list
        unique_user_list = list(dict.fromkeys(unique_user_list))

        retweeted_user = []
        for current_user in unique_user_list:
            for _user_list in retweet_user_list:
                # if there is break means user is not in every list
                if current_user not in _user_list:
                    break
            else:
                # if no break then user is in every list i.e eligible user
                retweeted_user.append(current_user)
        context['retweeted_user'] = retweeted_user
        return context

templates/base.html
{% load static %}
{% load tz %}
{% load l10n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="description"
    content="Authentium Tweet Retweet Reward Project" />
  <meta name="keywords" content="tweet, retweet, reward" />
  <meta name="author" content="satinder" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes, minimal-ui" />
  {% comment %}
  <meta http-equiv="refresh" content="3"> {% endcomment %}
  <title>{% block title %}Home{% endblock title %}</title>
  <!-- Fevicon -->
  <!-- Favicons -->
  <link rel="icon" href="{% static 'img/favicon.ico' %}" />

  <link rel="icon" href="{% static 'img/favicon.png' %}" />
{% block base_css %}

  {% include "base/css.html" %}
{% endblock base_css %}
  
  <style>
    .LoaderBalls {
      width: 90px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      position: fixed;
      z-index: 99999;
      left: 50%;
      top: 30%;
      transform: translate(-50%, -50%);
    }

    .LoaderBalls__item {
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: #0094ca;

    }

    .LoaderBalls__item:nth-child(1) {
      animation: bouncing 0.4s alternate infinite cubic-bezier(0.6, 0.05, 0.15, 0.95);
    }

    .LoaderBalls__item:nth-child(2) {
      animation: bouncing 0.4s 0.1s alternate infinite cubic-bezier(0.6, 0.05, 0.15, 0.95) backwards;
    }

    .LoaderBalls__item:nth-child(3) {
      animation: bouncing 0.4s 0.2s alternate infinite cubic-bezier(0.6, 0.05, 0.15, 0.95) backwards;
    }

    @keyframes bouncing {
      0% {
        transform: translate3d(0, 10px, 0) scale(1.2, 0.85);
      }

      100% {
        transform: translate3d(0, -20px, 0) scale(0.9, 1.1);
      }
    }
  </style>
  <script>
    document.onreadystatechange = function () {
      if (document.readyState !== "complete") {
        document.querySelector("body").style.visibility = "hidden";
        document.querySelector(".LoaderBalls").style.visibility = "visible";
      } else {
        document.querySelector(".LoaderBalls").style.display = "none";
        document.querySelector("body").style.visibility = "visible";
      }
    };  
  </script>
  <noscript>

    <style>
      /* noscript detects if javascript is disabled
		   if JavaScript not present, don't show loader */

      .LoaderBalls {
        display: none;
      }
    </style>

  </noscript>
</head>

<body class="vertical-layout">
  <div class="LoaderBalls">
    <!-- https://codepen.io/Sixclones/pen/VBdeXL -->
    <div class="LoaderBalls__item"></div>
    <div class="LoaderBalls__item"></div>
    <div class="LoaderBalls__item"></div>
  </div>
  {% block indexhtml %} {% endblock indexhtml %}

  {% include "base/js.html" %}
  {% block javascript%}
  {% endblock javascript%}


</body>

</html>

templates/base/css.html
{% load static %}

<!-- Start css -->

<!-- jQuery UI css -->
<link href="{% static 'assets/plugins/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet" type="text/css" />
<!-- jQuery Confirm css -->
<link href="{% static 'assets/plugins/jquery-confirm/css/jquery-confirm.css' %}" rel="stylesheet" type="text/css">

<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />

 <!-- Select2 css -->
 <link href="{% static 'assets/plugins/select2/select2.min.css' %}" rel="stylesheet" type="text/css" />
 <link href="{% static 'assets/plugins/select2/select2-bootstrap.min.css' %}" rel="stylesheet" type="text/css" />

<!-- main style css -->
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" type="text/css" />

<!-- Remix icon css -->
<link href="{% static 'assets/fonts/remixicon.css' %}" rel="stylesheet" type="text/css" />
{% comment %} 
<!-- Datepicker css -->
<link href="{% static 'assets/plugins/datepicker/datepicker.min.css' %}" rel="stylesheet" type="text/css" /> {% endcomment %}
{% comment %} <link href="{% static 'assets/plugins/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" type="text/css" /> {% endcomment %}
<link href="{% static 'assets/plugins/tempus-dominus/tempus-dominus.css' %}" rel="stylesheet" type="text/css" />


<!-- Datatable css -->
<link href="{% static 'assets/plugins/datatables/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />


<!-- Mystyle css -->
<link href="{% static 'css/mystyle.css' %}" rel="stylesheet" type="text/css" />


<!-- End css -->

templates/base/js.html
{% load static %}
<!-- End Containerbar -->
<!-- Start js -->
<script defer src="{% static 'assets/js/jquery.min.js' %}"></script>
<script defer src="{% static 'assets/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script defer src="{% static 'assets/js/popper.min.js' %}"></script>
<script defer src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
<script defer src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
<!-- jQuery Confirm js -->
<script defer src="{% static 'assets/plugins/jquery-confirm/js/jquery-confirm.js' %}"></script>

<!-- Select2 js -->
{% comment %} <script defer src="{% static 'assets/plugins/select2/select2.full.min.js' %}"></script> {% endcomment %}
<script defer src="{% static 'assets/plugins/select2/select2.min.js' %}"></script>

<!-- Datepicker JS -->
{% comment %} <script defer src="{% static 'assets/plugins/datepicker/datepicker.min.js' %}"></script>
<script defer src="{% static 'assets/plugins/datepicker/i18n/datepicker.en.js' %}"></script> {% endcomment %}
{% comment %} <script defer src="{% static 'assets/plugins/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js' %}"></script>  {% endcomment %}
<script defer src="{% static 'assets/plugins/tempus-dominus/tempus-dominus.js' %}"></script> 
<!-- Datatables JS -->
<script defer src="{% static 'assets/plugins/datatables/jquery.dataTables.min.js' %}"></script>

<!-- Myscript js -->
<script defer src="{% static 'js/myscript.js' %}"></script>

<!-- End js -->

templates/form_repeat.html
<div class="form-group col-md-{{col_md|default:"4"}} {{mr_lg_auto}} {{exclass}} ">
    <label for="{{f.id_for_label}}" class="col-sm-{{lcol|default:"6"}} {{lclass}} col-form-label font-weight-bold dark-theme-text">{{f_label}}</label>
    <div class="col-sm-12">
        {{f}}
    </div>
    {% if f.errors %} {% for ee in f.errors %}
    <span class="error-text text-center">
        {{ ee }}
    </span>
    {% endfor %} {% endif %}
</div>

templates/form_search_tweet.html
{% extends "index.html" %}
{% load static %} 
{% load crispy_forms_tags %} 
{% block title %}Search Tweet{% endblock title %} 

{% block content %}
<!-- Start container-fluid  -->
<div class="container-fluid pb-5 my-5">
    <!-- Start row -->
    <div class="row pt-4 d-flex justify-content-center">
        <h4>Search Tweet</h4>
      </div>
      <!-- End row -->
      
      <!-- Start row -->
      <div class="row justify-content-center">
        <!-- Start col -->
    <div class="col col-md-6">
      <form class="" action="" method="post">
          {% csrf_token %} {{form|crispy }}
  
          <div class="">
            <div class="col">
              <input
                class="btn btn-block btn-outline-dark"
                type="submit"
                value="Search"
              />
            </div>
          </div>
        </form>
      </div>
      <!-- End col -->
    </div>
    <!-- End row -->
    
    {% if search_tweets %}

    <!-- Start row -->
   <div class="row pt-4 d-flex justify-content-center">
    <h4>Search Result for {{form.query.value}}</h4>
  </div>
  <!-- End row -->
  <!-- Start row -->
  <div class="row pt-4 justify-content-center">
    {% for t in search_tweets %}
        <!-- Start col -->  
        <div class="col-12 p-lg-3 m-lg-2">
            <!-- Start row -->
            <div class="row p-2">
                <!-- Start col -->
                <div class="col-12 bg-white rounded shadow-sm">
                <!-- Start row -->
                <div class="row list-group-item d-flex">
                    <!-- Start col -->
                    <div class="col-1">
                    <img src="{{t.user.profile_image_url_https}}" class="img-fluid img-thumbnail" alt="{{t.user.name}}" srcset="">
                    </div>
                    <!-- End col -->
                    <!-- Start col -->
                    <div class="col-11">
                    <!-- Start row -->
                    <div class="row ">

                        <div class="col font-weight-bold d-flex">Tweet Details
                        <i data-toggle="tooltip" title="This detail is fetched from Tweeter API." class="ri-error-warning-line ri-xxs align-self-start"></i>
                        </div>
                    
                    </div>
                    <!-- End row -->
                    <!-- Start row -->
                    <div class="row list-group-item d-flex">
        
                        <div class="col">Text : {{t.text}}{% if t.truncated %}...{% endif %}</div>
                        
                    </div>
                    <!-- End row -->

                    <!-- Start row -->
                    <div class="row pt-3">

                        <div class="col font-weight-bold d-flex">User Details
                        <i data-toggle="tooltip" title="This detail is fetched from  Tweeter API." class="ri-error-warning-line ri-xxs align-self-start"></i>
                        </div>
                    </div>
                    <!-- End row -->
                    <!-- Start row -->
                    <div class="row list-group-item d-flex">
                        <div class="col">ID : {{t.user.id}}</div>
                        <div class="col">Name : {{t.user.name}}</div>
                        <div class="col">Screen Name : {{t.user.screen_name}}</div>
                        <div class="col">Location: {{t.user.location}}</div>
                        <div class="col">Verified: {{t.user.verified}}</div>
                        <div class="col">Following: {{t.user.following}}</div>
                        <div class="col">Created At : {{t.user.created_at}}</div>
                        <div class="col">Friends : {{t.user.friends_count}}</div>
                        <div class="col">Followers Count : {{t.user.followers_count}}</div>
                    </div>
                    
                    </div>
                    <!-- End col -->
                </div>
            </div>
            <!-- End col -->
            
        </div>
        <!-- End row -->
    </div>
    <!-- End col -->
        {% endfor %}
    </div>
    <!-- End row -->
    {% endif %}

  </div>
  <!-- End container-fluid  -->

  {% endblock content %} {% block javascript %} {% endblock javascript %}

templates/form_search_user.html
{% extends "index.html" %}
{% load static %} 
{% load crispy_forms_tags %} 
{% block title %}Search User{% endblock title %} 

{% block content %}
<!-- Start container-fluid  -->
<div class="container-fluid pb-5 my-5">
    <!-- Start row -->
    <div class="row pt-4 d-flex justify-content-center">
        <h4>Search Tweeter User</h4>
      </div>
      <!-- End row -->
      
      <!-- Start row -->
      <div class="row justify-content-center">
        <!-- Start col -->
    <div class="col col-md-6">
      <form class="" action="" method="post">
          {% csrf_token %} {{form|crispy }}
  
          <div class="">
            <div class="col">
              <input
                class="btn btn-block btn-outline-dark"
                type="submit"
                value="Search"
              />
            </div>
          </div>
        </form>
      </div>
      <!-- End col -->
    </div>
    <!-- End row -->
    
    {% if search_users %}

    <!-- Start row -->
   <div class="row pt-4 d-flex justify-content-center">
    <h4>Search Result for {{form.query.value}}</h4>
  </div>
  <!-- End row -->
  <!-- Start row -->
  <div class="row pt-4 justify-content-center">
    {% for t in search_users %}
        <!-- Start col -->  
        <div class="col-12 p-lg-3 m-lg-2">
            <!-- Start row -->
            <div class="row p-2">
                <!-- Start col -->
                <div class="col-12 bg-white rounded shadow-sm">
                <!-- Start row -->
                <div class="row list-group-item d-flex">
                    <!-- Start col -->
                    <div class="col-1">
                    <img src="{{t.profile_image_url_https}}" class="img-fluid img-thumbnail" alt="{{u.name}}" srcset="">
                    </div>
                    <!-- End col -->
                    <!-- Start col -->
                    <div class="col-11">
                    <!-- Start row -->
                    <div class="row ">

                        <div class="col font-weight-bold d-flex">Tweet Details
                        <i data-toggle="tooltip" title="This detail is fetched from Tweeter API." class="ri-error-warning-line ri-xxs align-self-start"></i>
                        </div>
                    
                    </div>
                    <!-- End row -->
                    <!-- Start row -->
                    <div class="row list-group-item d-flex">
        
                        <div class="col">Text : {{t.description}}</div>
                        
                    </div>
                    <!-- End row -->

                    <!-- Start row -->
                    <div class="row pt-3">

                        <div class="col font-weight-bold d-flex">User Details
                        <i data-toggle="tooltip" title="This detail is fetched from  Tweeter API." class="ri-error-warning-line ri-xxs align-self-start"></i>
                        </div>
                    </div>
                    <!-- End row -->
                    <!-- Start row -->
                    <div class="row list-group-item d-flex">
                        <div class="col">ID : {{t.id}}</div>
                        <div class="col">Name : {{t.name}}</div>
                        <div class="col">Screen Name : {{t.screen_name}}</div>
                        <div class="col">Location: {{t.location}}</div>
                        <div class="col">Verified: {{t.verified}}</div>
                        <div class="col">Following: {{t.following}}</div>
                        <div class="col">Created At : {{t.created_at}}</div>
                        <div class="col">Friends : {{t.friends_count}}</div>
                        <div class="col">Followers Count : {{t.followers_count}}</div>
                    </div>
                    
                    </div>
                    <!-- End col -->
                </div>
            </div>
            <!-- End col -->
            
        </div>
        <!-- End row -->
    </div>
    <!-- End col -->
        {% endfor %}
    </div>
    <!-- End row -->
    {% endif %}

  </div>
  <!-- End container-fluid  -->

  {% endblock content %} {% block javascript %} {% endblock javascript %}

templates/getprams.html
{% block getprams %}
{% if page and fp %}?page={{page}}
{% for p,v in request.GET.items %}
{% if p != 'page' and v != "" %}&{{p}}={{v}}{% endif %}
{% endfor %}
{% elif fp %}{% if request.GET %}?{% endif %}
{% for p,v in request.GET.items %}
{% if p != 'page' and v != "" %}{% if not forloop.first %}&{% endif %}{{p}}={{v}}{% endif %}
{% endfor %}
{% else %}{% if request.GET %}?{% endif %}
{% for p,v in request.GET.items %}
{% if v != "" %}{% if not forloop.first %}&{% endif %}{{p}}={{v}}{% endif %}
{% endfor %}
{% endif %}
{% endblock getprams %}

templates/home.html
{% extends "index.html" %}
{% load static %}
{% block title %} DashBoard{% endblock title %} 

{% block content %}
<!-- Start container-fluid  -->
<div class="container-fluid pb-5 my-5">
  
  <!-- Start row -->
  <div class="row pt-4 justify-content-center">
   
    <!-- Start col -->
    <div class="col my-md-3 col-md-3">
      <a
        type="button"
        class="btn btn-block text-center p-3 bg-secondary font-weight-bold"
        role="button"
        href="{% url 'tweetapp:retweets_of_me' %}"
        data-toggle="tooltip"
        title="The list of retweeted tweet."
      >The Retweeted Tweets
      </a>
    </div>
    <!-- End col -->
     <!-- Start col -->
     <div class="col my-md-3 col-md-3">
      <a
        type="button"
        class="btn btn-block text-center p-3 bg-secondary font-weight-bold"
        role="button"
        href="{% url 'tweetapp:retweeted_user' %}"
        data-toggle="tooltip"
        title="The list of users who have retweeted your every tweet."
      >Retweeted User
      </a>
    </div>
    <!-- End col -->
  
    <!-- Start col -->
    <div class="col my-md-3 col-md-3">
      <a
        type="button"
        class="btn btn-block text-center p-3 bg-secondary font-weight-bold"
        role="button"
        href="{% url 'tweetapp:search_user' %}"
        data-toggle="tooltip"
        title="The list of retweeted tweet."
      >Search Tweeter user
      </a>
    </div>
    <!-- End col -->

    <!-- Start col -->
    <div class="col my-md-3 col-md-3">
      <a
        type="button"
        class="btn btn-block text-center p-3 bg-secondary font-weight-bold"
        role="button"
        href="{% url 'tweetapp:search_tweet' %}"
        data-toggle="tooltip"
        title="The list of retweeted tweet."
      >Search Tweet
      </a>
    </div>
    <!-- End col -->
  
</div>
<!-- End row -->



  
  </div>
  <!-- End container-fluid  -->

  {% endblock content %} {% block javascript %} {% endblock javascript %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block base_css %}
{{block.super}}
{% endblock base_css %}
{% block indexhtml %}
    <!-- Start Topbar -->
    <div class="topbar w-100">
        <!-- Start row -->
        <div class="row align-items-center">
        <!-- Start col -->
        <div class="col-md-12 align-self-center">
            <div class="menubar d-inline">
            <a class="menu-hamburger d-flex align-items-center font-weight-bold"  href="{% url 'tweetapp:home' %}">
                Home<i class="ri-home-2-fill px-1"></i>
            </a>
            </div>
        </div>
        <!-- End col -->
        </div>
        <!-- End row -->
    </div>
    <!-- End Topbar -->
    {% if messages %}
    <!-- Start container-fluid  -->
<div class="container-fluid mt-5 mb-n5">
  <!-- Start row -->
  <div class="row pt-4 d-flex justify-content-center">
    <ul class="messages">
      {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible text-dark font-weight-bold"
        role="alert"
      >
        {{ message }}
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
    </ul>
  </div>
  <!-- End row -->
  <!-- Start row -->
  
</div>
<!-- End container-fluid  -->
{% endif %}

    {% block content %}



    {% endblock content %}

    <!-- Start Footer -->
    <div class="d-flex justify-content-center mt-5 pt-5 pt-md-0">
        <div class="footerbar text-dark pt-5 pt-md-0">

            <a target="_blank" rel="noopener noreferrer" href="https://docs.tweepy.org/en/stable/api.html/">Explore other twitter API Endoint</a> |
         </div>
      </div>
      <!-- End Footer -->
<script type="text/javascript">
    let static = "{% static 'colorscheme/css' %}"
</script>
{% endblock indexhtml %}

templates/retweeted_tweet_list.html
{% extends "index.html" %}
{% load static %}
{% block title %} Retweeted Tweet {% endblock title %} 

{% block content %}
<!-- Start container-fluid  -->
<div class="container-fluid pb-5 my-5">
   <!-- Start row -->
   <div class="row pt-4 d-flex justify-content-center">
    <h4>The Retweeted Tweet List</h4>
  </div>
  <!-- End row -->
  <!-- Start row -->
  <div class="row pt-4 justify-content-center">
    {% for t in get_retweets_of_me %}
        <!-- Start col -->  
        <div class="col-12 p-lg-3 m-lg-2">
            <!-- Start row -->
            <div class="row p-2">
                <!-- Start col -->
                <div class="col-12 bg-white rounded shadow-sm">
                <!-- Start row -->
                <div class="row list-group-item d-flex">
                    <!-- Start col -->
                    <div class="col-1">
                    <img src="{{t.user.profile_image_url_https}}" class="img-fluid img-thumbnail" alt="{{u.user.name}}" srcset="">
                    </div>
                    <!-- End col -->
                    <!-- Start col -->
                    <div class="col-11">
                    <!-- Start row -->
                    <div class="row ">

                        <div class="col font-weight-bold d-flex">Tweet Details
                        <i data-toggle="tooltip" title="This detail is fetched from Tweeter API." class="ri-error-warning-line ri-xxs align-self-start"></i>
                        </div>
                    
                    </div>
                    <!-- End row -->
                    <!-- Start row -->
                    <div class="row list-group-item d-flex">
        
                        <div class="col">ID : {{t.id}}</div>
                        <div class="col">Text : {{t.text}}</div>
                        <div class="col">Created At : {{t.created_at}}</div>
                        <div class="col"> <a target="_blank" rel="noopener noreferrer" href="{% url 'tweetapp:retweet_user_list' tweet_id=t.id %}">Users That Retweeted This Tweet</a></div>
                        
                    </div>
                    <!-- End row -->

                    <!-- Start row -->
                    <div class="row pt-3">

                        <div class="col font-weight-bold d-flex">User Details
                        <i data-toggle="tooltip" title="This detail is fetched from  Tweeter API." class="ri-error-warning-line ri-xxs align-self-start"></i>
                        </div>
                    </div>
                    <!-- End row -->
                    <!-- Start row -->
                    <div class="row list-group-item d-flex">
                        <div class="col">ID : {{t.user.id}}</div>
                        <div class="col">Name : {{t.user.name}}</div>
                        <div class="col">Screen Name : {{t.user.screen_name}}</div>
                        <div class="col">Created At : {{t.user.created_at}}</div>
                    </div>
                    
                    </div>
                    <!-- End col -->
                </div>
            </div>
            <!-- End col -->
            
        </div>
        <!-- End row -->
    </div>
    <!-- End col -->
        {% endfor %}
    </div>
    <!-- End row -->



  
  </div>
  <!-- End container-fluid  -->

  {% endblock content %} {% block javascript %} {% endblock javascript %}